/**
 * Curated verbatim quote bank for the preset flow. Each preset maps to a
 * `quoteCategory` here (see `constants/presets.ts`); the quote carousel
 * shows the user real, hand-picked quotes to choose from — no AI generation.
 *
 * Source: 180 quotes, 20 per category, transcribed verbatim (including
 * original language — the `social-media` category is intentionally German).
 */

export interface Quote {
  id: string;
  category: string;
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { id: 'motivation-1', category: 'motivation', text: 'Work hard in silence, let your success be your noise.', author: 'Anonymous' },
  { id: 'motivation-2', category: 'motivation', text: 'If you want something you have never had, you must be willing to do something you have never done.', author: 'Thomas Jefferson' },
  { id: 'motivation-3', category: 'motivation', text: 'Life begins at the end of your comfort zone.', author: 'Neale Donald Walsch' },
  { id: 'motivation-4', category: 'motivation', text: 'Two things define you: Your patience when you have nothing and your attitude when you have everything.', author: 'Imam Ali' },
  { id: 'motivation-5', category: 'motivation', text: 'The greatest pleasure in life is doing what people say you cannot do.', author: 'Walter Bagehot' },
  { id: 'motivation-6', category: 'motivation', text: 'Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.', author: 'Earl Nightingale' },
  { id: 'motivation-7', category: 'motivation', text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { id: 'motivation-8', category: 'motivation', text: 'A river cuts through rock, not because of its power, but because of its persistence.', author: 'Jim Watkins' },
  { id: 'motivation-9', category: 'motivation', text: 'If it is important to you, you will find a way. If not, you\'ll find an excuse.', author: 'Ryan Blair' },
  { id: 'motivation-10', category: 'motivation', text: 'Great minds discuss ideas. Average minds discuss events. Small minds discuss people.', author: 'Eleanor Roosevelt' },
  { id: 'motivation-11', category: 'motivation', text: 'If people are not laughing at your goals, your goals are too small.', author: 'Azim Premji' },
  { id: 'motivation-12', category: 'motivation', text: 'Hard work beats talent when talent doesn\'t work hard.', author: 'Tim Notke' },
  { id: 'motivation-13', category: 'motivation', text: 'I am not what happened to me, I am what I choose to become.', author: 'C.G. Jung' },
  { id: 'motivation-14', category: 'motivation', text: 'An entire sea of water can\'t sink a ship unless it gets inside the ship. Similarly, the negativity of the world can\'t put you down unless you allow it to get inside you.', author: 'Goi Nasu' },
  { id: 'motivation-15', category: 'motivation', text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { id: 'motivation-16', category: 'motivation', text: 'If you want to live a happy life, tie it to a goal, not to people or things.', author: 'Albert Einstein' },
  { id: 'motivation-17', category: 'motivation', text: 'Doubt kills more dreams than failure ever will.', author: 'Suzy Kassem' },
  { id: 'motivation-18', category: 'motivation', text: 'Knowing is not enough, we must apply. Willing is not enough, we must do.', author: 'Bruce Lee' },
  { id: 'motivation-19', category: 'motivation', text: 'The first step to getting anywhere is deciding you\'re no longer willing to stay where you are.', author: 'Anonymous' },
  { id: 'motivation-20', category: 'motivation', text: 'If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.', author: 'Lao Tzu' },
  { id: 'gratitude-1', category: 'gratitude', text: 'The more you are grateful for what you have the more you will have to be grateful for.', author: 'Zig Ziglar' },
  { id: 'gratitude-2', category: 'gratitude', text: 'Be thankful for what you have; you\'ll end up having more. If you concentrate on what you don\'t have, you will never, ever have enough.', author: 'Oprah Winfrey' },
  { id: 'gratitude-3', category: 'gratitude', text: 'Gratitude unlocks the fullness of life. It turns what we have into enough, and more.', author: 'Melody Beattie' },
  { id: 'gratitude-4', category: 'gratitude', text: 'The greatest thing is to give thanks for everything.', author: 'Albert Schweitzer' },
  { id: 'gratitude-5', category: 'gratitude', text: 'Gratitude is a powerful process for shifting your energy and bringing more of what you want into your life.', author: 'Rhonda Byrne' },
  { id: 'gratitude-6', category: 'gratitude', text: 'Gratitude is the single most important ingredient to living a successful and fulfilled life.', author: 'Jack Canfield' },
  { id: 'gratitude-7', category: 'gratitude', text: 'Appreciating what shows up in your life changes your personal vibration. Gratitude elevates your life to a higher frequency.', author: 'Oprah Winfrey' },
  { id: 'gratitude-8', category: 'gratitude', text: 'That\'s the way life works: gratitude and appreciation just bring more goodness. Remember: Everything we give out comes back.', author: 'Louise Hay' },
  { id: 'gratitude-9', category: 'gratitude', text: 'Acknowledging the good that you already have in your life is the foundation for all abundance.', author: 'Eckhart Tolle' },
  { id: 'gratitude-10', category: 'gratitude', text: 'When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love.', author: 'Marcus Aurelius' },
  { id: 'gratitude-11', category: 'gratitude', text: 'My father gave me the greatest gift anyone could give another person, he believed in me.', author: 'Jim Valvano' },
  { id: 'gratitude-12', category: 'gratitude', text: 'Waking up this morning, I smile. Twenty-four brand new hours are before me. I vow to live fully in each moment and to look at all beings with eyes of compassion.', author: 'Thich Nhat Hanh' },
  { id: 'gratitude-13', category: 'gratitude', text: 'The more you praise and celebrate your life, the more there is in life to celebrate.', author: 'Oprah Winfrey' },
  { id: 'gratitude-14', category: 'gratitude', text: 'What if you woke up this morning and had only the things you thanked God for yesterday?', author: 'Max Lucado' },
  { id: 'gratitude-15', category: 'gratitude', text: 'My day begins and ends with gratitude and joy.', author: 'Louise Hay' },
  { id: 'gratitude-16', category: 'gratitude', text: 'I am so grateful for my beautiful life. I am cherished and loved. And I share my love and joy with everyone.', author: 'Louise Hay' },
  { id: 'gratitude-17', category: 'gratitude', text: 'It is always possible to be thankful for what is given rather than to complain about what is not given. One or the other becomes a habit of life.', author: 'Elisabeth Elliot' },
  { id: 'gratitude-18', category: 'gratitude', text: 'I would maintain that thanks are the highest form of thought, and that gratitude is happiness doubled by wonder.', author: 'Gilbert K. Chesterton' },
  { id: 'gratitude-19', category: 'gratitude', text: 'The real gift of gratitude is that the more grateful you are, the more present you become.', author: 'Robert Holden' },
  { id: 'gratitude-20', category: 'gratitude', text: 'Every breath we draw is a gift of God\'s love; every moment of existence is a grace.', author: 'Thomas Merton' },
  { id: 'focus-1', category: 'focus', text: 'Stay focused.', author: 'Get It Done' },
  { id: 'focus-2', category: 'focus', text: 'Focus on the solution, not on the problem.', author: 'Jim Rohn' },
  { id: 'focus-3', category: 'focus', text: 'Ignore the noise, focus on your work.', author: 'Anonymous' },
  { id: 'focus-4', category: 'focus', text: 'A goal without a plan is just a wish.', author: 'Antoine de Saint-Exupéry' },
  { id: 'focus-5', category: 'focus', text: 'Don\'t think about what can happen in a month. Don\'t think about what can happen in a year. Just focus on the 24 hours in front of you and do what you can to get closer to where you want to be.', author: 'Eric Thomas' },
  { id: 'focus-6', category: 'focus', text: 'What you focus on grows.', author: 'Esther Hicks' },
  { id: 'focus-7', category: 'focus', text: 'Always remember, your focus determines your reality.', author: 'George Lucas' },
  { id: 'focus-8', category: 'focus', text: 'Stay focused, ignore the distractions, and you will accomplish your goals much faster.', author: 'Joel Osteen' },
  { id: 'focus-9', category: 'focus', text: 'Don\'t make excuses for why you can\'t get it done. Focus on all the reasons why you must make it happen.', author: 'Ralph Marston' },
  { id: 'focus-10', category: 'focus', text: 'Focus on your strengths, not your weaknesses.', author: 'Gary Vaynerchuk' },
  { id: 'focus-11', category: 'focus', text: 'Focus like a laser, not a flashlight.', author: 'Michael Jordan' },
  { id: 'focus-12', category: 'focus', text: 'Where focus goes, energy flows.', author: 'Tony Robbins' },
  { id: 'focus-13', category: 'focus', text: 'Only through focus can you do world-class things, no matter how capable you are.', author: 'Bill Gates' },
  { id: 'focus-14', category: 'focus', text: 'FOCUS - Follow One Course Until Successful.', author: 'Robert T. Kiyosaki' },
  { id: 'focus-15', category: 'focus', text: 'If there are nine rabbits on the ground and you want to catch one, just focus on one.', author: 'Jack Ma' },
  { id: 'focus-16', category: 'focus', text: 'Whatever you focus on is what you get.', author: 'Tony Robbins' },
  { id: 'focus-17', category: 'focus', text: 'The time that leads to mastery is dependent on the intensity of our focus.', author: 'Robert Greene' },
  { id: 'focus-18', category: 'focus', text: 'When you focus on problems, you get more problems. When you focus on possibilities, you have more opportunities.', author: 'Zig Ziglar' },
  { id: 'focus-19', category: 'focus', text: 'Change your focus from making money to serving more people. Serving people makes the money come in.', author: 'Robert T. Kiyosaki' },
  { id: 'focus-20', category: 'focus', text: 'What you focus on grows. What you concentrate on is what you see more of in your life.', author: 'Robin S. Sharma' },
  { id: 'mindfulness-1', category: 'mindfulness', text: 'Be the silent watcher of your thoughts and behavior. You are beneath the thinker. You are the stillness beneath the mental noise. You are the love and joy beneath the pain.', author: 'Eckhart Tolle' },
  { id: 'mindfulness-2', category: 'mindfulness', text: 'Nothing is worth more than this day. You cannot relive yesterday. Tomorrow is still beyond your reach.', author: 'Johann Wolfgang von Goethe' },
  { id: 'mindfulness-3', category: 'mindfulness', text: 'Welcome to the present moment. Here. Now. The only moment there ever is.', author: 'Eckhart Tolle' },
  { id: 'mindfulness-4', category: 'mindfulness', text: 'Happiness is your nature. It is not wrong to desire it. What is wrong is seeking it outside when it is inside.', author: 'Ramana Maharshi' },
  { id: 'mindfulness-5', category: 'mindfulness', text: 'Confine yourself to the present.', author: 'Marcus Aurelius' },
  { id: 'mindfulness-6', category: 'mindfulness', text: 'Mindfulness isn\'t difficult, we just need to remember to do it.', author: 'Sharon Salzberg' },
  { id: 'mindfulness-7', category: 'mindfulness', text: 'Mindfulness is the miracle by which we master and restore ourselves.', author: 'Nhat Hanh' },
  { id: 'mindfulness-8', category: 'mindfulness', text: 'Wisdom comes with the ability to be still. Just look and just listen. No more is needed.', author: 'Eckhart Tolle' },
  { id: 'mindfulness-9', category: 'mindfulness', text: 'Breathing in, I calm body and mind. Breathing out, I smile. Dwelling in the present moment I know this is the only moment.', author: 'Thich Nhat Hanh' },
  { id: 'mindfulness-10', category: 'mindfulness', text: 'When you go deeply into the present, gratitude arises spontaneously, even if it\'s just gratitude for breathing.', author: 'Eckhart Tolle' },
  { id: 'mindfulness-11', category: 'mindfulness', text: 'Mindfulness is a pause - the space between stimulus and response: that\'s where choice lies.', author: 'Tara Brach' },
  { id: 'mindfulness-12', category: 'mindfulness', text: 'Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.', author: 'Thich Nhat Hanh' },
  { id: 'mindfulness-13', category: 'mindfulness', text: 'The most precious gift we can offer anyone is our attention. When mindfulness embraces those we love, they will bloom like flowers.', author: 'Thich Nhat Hanh' },
  { id: 'mindfulness-14', category: 'mindfulness', text: 'Mindfulness means paying attention in a particular way: on purpose, in the present moment, and non-judgmentally.', author: 'Jon Kabat-Zinn' },
  { id: 'mindfulness-15', category: 'mindfulness', text: 'Life is available only in the present moment.', author: 'Nhat Hanh' },
  { id: 'mindfulness-16', category: 'mindfulness', text: 'As soon as you honor the present moment, all unhappiness and struggle dissolve, and life begins to flow with joy and ease.', author: 'Eckhart Tolle' },
  { id: 'mindfulness-17', category: 'mindfulness', text: 'Breathing in, there is only the present moment. Breathing out, it is a wonderful moment.', author: 'Thich Nhat Hanh' },
  { id: 'mindfulness-18', category: 'mindfulness', text: 'Breath is the bridge which connects life to consciousness, which unites your body to your thoughts.', author: 'Thich Nhat Hanh' },
  { id: 'mindfulness-19', category: 'mindfulness', text: 'To meditate with mindful breathing is to bring body and mind back to the present moment so that you do not miss your appointment with life.', author: 'Nhat Hanh' },
  { id: 'mindfulness-20', category: 'mindfulness', text: 'Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves - slowly, evenly, without rushing toward the future.', author: 'Thich Nhat Hanh' },
  { id: 'humor-1', category: 'humor', text: 'Why join the navy if you can be a pirate?', author: 'Steve Jobs' },
  { id: 'humor-2', category: 'humor', text: 'The road to success is always under construction.', author: 'Lily Tomlin' },
  { id: 'humor-3', category: 'humor', text: 'The real trouble with reality is that there is no background music.', author: 'Anonymous' },
  { id: 'humor-4', category: 'humor', text: 'I need a six month vacation twice a year.', author: 'Anonymous' },
  { id: 'humor-5', category: 'humor', text: 'Always forgive your enemies; nothing annoys them so much.', author: 'Oscar Wilde' },
  { id: 'humor-6', category: 'humor', text: 'If at first you don\'t succeed, destroy all evidence that you tried.', author: 'Steven Wright' },
  { id: 'humor-7', category: 'humor', text: 'The best way to appreciate your job is to imagine yourself without one.', author: 'Oscar Wilde' },
  { id: 'humor-8', category: 'humor', text: 'The trouble with being in the rat race is that even if you win, you\'re still a rat.', author: 'Lily Tomlin' },
  { id: 'humor-9', category: 'humor', text: 'The best things in life are free. The second best are very expensive.', author: 'Coco Chanel' },
  { id: 'humor-10', category: 'humor', text: 'Never try to teach a pig to sing; it wastes your time and it annoys the pig.', author: 'Robert A. Heinlein' },
  { id: 'humor-11', category: 'humor', text: 'A successful person is one who can lay a firm foundation with the bricks others have thrown at them.', author: 'David Brinkley' },
  { id: 'humor-12', category: 'humor', text: 'The only place success comes before work is in the dictionary.', author: 'Vince Lombardi' },
  { id: 'humor-13', category: 'humor', text: 'Dear Karma, I have a list of people that you missed.', author: 'Anonymous' },
  { id: 'humor-14', category: 'humor', text: 'The road to success is dotted with many tempting parking spaces.', author: 'Will Rogers' },
  { id: 'humor-15', category: 'humor', text: 'Give a man a fire and he\'s warm for a day, but set fire to him and he\'s warm for the rest of his life.', author: 'Terry Pratchett' },
  { id: 'humor-16', category: 'humor', text: 'Due to budget cuts the light at the end of the tunnel has been turned off.', author: 'Aaron Paul' },
  { id: 'humor-17', category: 'humor', text: 'Money can\'t buy you happiness but it does bring you a more pleasant form of misery.', author: 'Spike Milligan' },
  { id: 'humor-18', category: 'humor', text: 'Monday is an awful way to spend 1/7 of your life.', author: 'Steven Wright' },
  { id: 'humor-19', category: 'humor', text: 'I\'d kill for a Nobel Peace Prize.', author: 'Steven Wright' },
  { id: 'humor-20', category: 'humor', text: 'If I had asked people what they wanted, they would have said faster horses.', author: 'Henry Ford' },
  { id: 'confidence-1', category: 'confidence', text: 'If you don\'t ask, the answer is always no.', author: 'Nora Roberts' },
  { id: 'confidence-2', category: 'confidence', text: 'You were not born a winner, and you were not born a loser. You are what you make yourself be.', author: 'Lou Holtz' },
  { id: 'confidence-3', category: 'confidence', text: 'Education breeds confidence. Confidence breeds hope. Hope breeds peace.', author: 'Confucius' },
  { id: 'confidence-4', category: 'confidence', text: 'Happiness and confidence are the prettiest things you can wear.', author: 'Taylor Swift' },
  { id: 'confidence-5', category: 'confidence', text: 'A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power.', author: 'Brian Tracy' },
  { id: 'confidence-6', category: 'confidence', text: 'If you haven\'t confidence in self, you are twice defeated in the race of life. With confidence, you have won even before you have started.', author: 'Marcus Garvey' },
  { id: 'confidence-7', category: 'confidence', text: 'You wouldn\'t worry so much about what others think of you if you realized how seldom they do.', author: 'Eleanor Roosevelt' },
  { id: 'confidence-8', category: 'confidence', text: 'Knock the \'t\' off the \'can\'t.\'', author: 'Samuel Johnson' },
  { id: 'confidence-9', category: 'confidence', text: 'Confidence is contagious. So is lack of confidence.', author: 'Vince Lombardi' },
  { id: 'confidence-10', category: 'confidence', text: 'You have within you right now, everything you need to deal with whatever the world can throw at you.', author: 'Brian Tracy' },
  { id: 'confidence-11', category: 'confidence', text: 'Believing that you\'re enough is what gives you the courage to be authentic.', author: 'Brené Brown' },
  { id: 'confidence-12', category: 'confidence', text: 'I know who I am, I know what I believe, that\'s all I need to know. From there, you do what you need to do.', author: 'Will Smith' },
  { id: 'confidence-13', category: 'confidence', text: 'You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.', author: 'Eleanor Roosevelt' },
  { id: 'confidence-14', category: 'confidence', text: 'If you\'re presenting yourself with confidence, you can pull off pretty much anything.', author: 'Katy Perry' },
  { id: 'confidence-15', category: 'confidence', text: 'My mother said to me, \'If you are a soldier, you will become a general. If you are a monk, you will become the Pope.\' Instead, I was a painter, and became Picasso.', author: 'Pablo Picasso' },
  { id: 'confidence-16', category: 'confidence', text: 'There can be no friendship without confidence, and no confidence without integrity.', author: 'Samuel Johnson' },
  { id: 'confidence-17', category: 'confidence', text: 'Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric.', author: 'Bertrand Russell' },
  { id: 'confidence-18', category: 'confidence', text: 'Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence.', author: 'George Washington' },
  { id: 'confidence-19', category: 'confidence', text: 'Confidence is going after Moby Dick in a rowboat and taking the tartar sauce with you.', author: 'Zig Ziglar' },
  { id: 'confidence-20', category: 'confidence', text: 'The mind, ever the willing servant, will respond to boldness, for boldness, in effect, is a command to deliver mental resources.', author: 'Norman Vincent Peale' },
  { id: 'curiosity-1', category: 'curiosity', text: 'Your curiosity is your growth point. Always.', author: 'Danielle LaPorte' },
  { id: 'curiosity-2', category: 'curiosity', text: 'Nobody ever figures out what life is all about, and it doesn\'t matter. Explore the world. Nearly everything is really interesting if you go into it deeply enough.', author: 'Richard P. Feynman' },
  { id: 'curiosity-3', category: 'curiosity', text: 'Curiosity is one of the most permanent and certain characteristics of a vigorous intellect.', author: 'Samuel Johnson' },
  { id: 'curiosity-4', category: 'curiosity', text: 'I suppose the one quality in an astronaut more powerful than any other is curiosity. They have to get some place nobody\'s ever been.', author: 'John Glenn' },
  { id: 'curiosity-5', category: 'curiosity', text: 'Wonder is the beginning of wisdom.', author: 'Socrates' },
  { id: 'curiosity-6', category: 'curiosity', text: 'To be interesting, be interested.', author: 'Dale Carnegie' },
  { id: 'curiosity-7', category: 'curiosity', text: 'My alma mater was books, a good library. I could spend the rest of my life reading, just satisfying my curiosity.', author: 'Malcolm X' },
  { id: 'curiosity-8', category: 'curiosity', text: 'A mind is like a parachute. It doesn\'t work if it is not open.', author: 'Frank Zappa' },
  { id: 'curiosity-9', category: 'curiosity', text: 'Always walk through life as if you have something new to learn, and you will.', author: 'Vernon Howard' },
  { id: 'curiosity-10', category: 'curiosity', text: 'Stay curious, keep learning and keep growing. And always strive to be more interested than interesting.', author: 'Jane Fonda' },
  { id: 'curiosity-11', category: 'curiosity', text: 'It\'s a crazy world out there. Be curious.', author: 'Stephen Hawking' },
  { id: 'curiosity-12', category: 'curiosity', text: 'I am just a child who has never grown up. I still keep asking these \'how\' and \'why\' questions. Occasionally, I find an answer.', author: 'Stephen Hawking' },
  { id: 'curiosity-13', category: 'curiosity', text: 'Ideas come from curiosity.', author: 'Walt Disney' },
  { id: 'curiosity-14', category: 'curiosity', text: 'Everyone should have their mind blown once a day.', author: 'Neil deGrasse Tyson' },
  { id: 'curiosity-15', category: 'curiosity', text: 'Research is formalized curiosity. It is poking and prying with a purpose.', author: 'Zora Neale Hurston' },
  { id: 'curiosity-16', category: 'curiosity', text: 'Everyone you will ever meet knows something you don\'t.', author: 'Bill Nye' },
  { id: 'curiosity-17', category: 'curiosity', text: 'Curiosity keeps leading us down new paths.', author: 'Walt Disney' },
  { id: 'curiosity-18', category: 'curiosity', text: 'Once a year go somewhere you have never been before.', author: 'Dalai Lama XIV' },
  { id: 'curiosity-19', category: 'curiosity', text: 'The true delight is in the finding out rather than in the knowing.', author: 'Isaac Asimov' },
  { id: 'curiosity-20', category: 'curiosity', text: 'The most exciting phrase to hear in science, the one that heralds the most discoveries, is not \'Eureka!\' but \'That\'s funny...\'', author: 'Isaac Asimov' },
  { id: 'social-media-1', category: 'social-media', text: 'Lasst einfach die Scheiße. Und auch wenn ihr mal vorhabt, in die Spielhalle oder ins Kasino zu gehen: Das ist Gift - für dich, für deinen Körper, und das brauchst du einfach nicht.', author: 'MontanaBlack' },
  { id: 'social-media-2', category: 'social-media', text: 'Was irgendein Random, der mich nicht kennt, denkt, ist mir scheißegal. Aber Freunde und Familie - das ist das wichtigste im Leben.', author: 'MontanaBlack' },
  { id: 'social-media-3', category: 'social-media', text: 'Die Realität ist nicht \'Beruf: YouTuber\'. Die Realität ist \'Beruf: Arzt, Anwalt, Einzelhandelskaufmann\'. Ich war nur zur richtigen Zeit am richtigen Ort und hab\' Glück gehabt.', author: 'MontanaBlack' },
  { id: 'social-media-4', category: 'social-media', text: 'Der menschliche Körper ist völlig verbuggt. Wie kann man so unendlich viele Jahre Evolution hinter sich haben und sich einfach auf die scheiß Zunge oder in die Wange beißen?', author: 'Trymacs' },
  { id: 'social-media-5', category: 'social-media', text: 'Wenn der Jungler gankt und stirbt, dann hast du den 30 Minuten lang im Textchat durchzubeleidigen und du bist auch noch nach dem Spiel stinksauer.', author: 'Trymacs' },
  { id: 'social-media-6', category: 'social-media', text: 'An alle die vielleicht auch ein Problem haben: Es muss selber im Kopf \'klick\' machen. Erst dann kann man sich bessern.', author: 'MontanaBlack' },
  { id: 'social-media-7', category: 'social-media', text: 'Es gibt eine Grenze zwischen Beleidigung und Satire. Mich zu kritisieren oder zu beleidigen ist das Eine, aber meine Community als Teil einer rechten Bewegung zu diffamieren, sprengt jeglich Grenzen. Da spricht wohl der Neid einer gescheiterten Karriere heraus.', author: 'MontanaBlack' },
  { id: 'social-media-8', category: 'social-media', text: 'Es gibt so viele wichtige Dinge im Leben, aber die Leute haben einfach zu viel Zeit, um sich mit Dingen auseinander zu setzen, die gar keine Aufmerksamkeit verdient haben. Und Gendern ist ganz weit oben an der Spitze. Braucht kein Mensch. Hat vorher alles super funktioniert.', author: 'MontanaBlack' },
  { id: 'social-media-9', category: 'social-media', text: 'McDonalds und Burger King sind absoluter Schmutz.', author: 'MontanaBlack' },
  { id: 'social-media-10', category: 'social-media', text: 'Ich sag\' euch ganz ehrlich: Ich wäre für \'ne Impfpflicht in Deutschland. Einfach weil ich kein Bock hab\', dass es noch fünf Jahre so geht.', author: 'MontanaBlack' },
  { id: 'social-media-11', category: 'social-media', text: 'Wenn man Scheiße macht, muss man sie dann auch ausbaden und das ist meistens nicht so angenehm.', author: 'MontanaBlack' },
  { id: 'social-media-12', category: 'social-media', text: 'Ihr wisst ja wie die Bockwurst knackt, Freunde.', author: 'MontanaBlack' },
  { id: 'social-media-13', category: 'social-media', text: 'Ehre genommen. Vorhaut genommen. Leben genommen.', author: 'MontanaBlack' },
  { id: 'social-media-14', category: 'social-media', text: 'Max: \'Wurdet ihr schon mal von einer Frau angegriffen?\' Sascha und Varion: \'Nee.\' Max: \'Ja okay, dann ich auch nicht.\'', author: 'Trymacs' },
  { id: 'social-media-15', category: 'social-media', text: 'Das Ding ging in allen Telegram Gruppen viral und hat, wie Motten, die in das Licht fliegen, Querdenker angelockt. Es ist eine Symphonie was es hier für Kommentare gibt.', author: 'Trymacs' },
  { id: 'social-media-16', category: 'social-media', text: 'Ich wünsche allen Geimpften ein frohes neues Jahr!', author: 'Trymacs' },
  { id: 'social-media-17', category: 'social-media', text: 'Es gibt zwei Sachen, die ich gut finde: Erste Sache ist, Leute zu unterhalten, damit sie was zum Lachen haben. Und die zweite ist, meine Reichweite dafür zu nutzen, Leute sauer zu machen.', author: 'Trymacs' },
  { id: 'social-media-18', category: 'social-media', text: 'Ich hab\' nicht getroffen... weil ich daneben geschossen hab\'.', author: 'Trymacs' },
  { id: 'social-media-19', category: 'social-media', text: 'Immer wenn ich in den Top 10 bin, muss ich auf einmal total auf\'s Klo. Und dann ist das Spiel vorbei und dann muss ich überhaupt nicht mehr. Das ist einfach nur Nervositätskack. Warum ist der menschliche Körper so verbuggt?', author: 'Trymacs' },
  { id: 'social-media-20', category: 'social-media', text: 'Wer jetzt, nachdem Corona fast ein Jahr existiert, immer noch nicht die Nase einpacken kann - ich geb\' den Leuten drei Monate und wenn ich dann nochmal \'ne Nase sehe, dann schlag ich einfach nur zu. Die Nasen, die rausgucken, werden gebrochen!', author: 'Trymacs' },
  { id: 'wisdom-1', category: 'wisdom', text: 'Any fool can know. The point is to understand.', author: 'Albert Einstein' },
  { id: 'wisdom-2', category: 'wisdom', text: 'Judge a man by his questions rather than by his answers.', author: 'Voltaire' },
  { id: 'wisdom-3', category: 'wisdom', text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  { id: 'wisdom-4', category: 'wisdom', text: 'To acquire knowledge, one must study; but to acquire wisdom, one must observe.', author: 'Marilyn Vos Savant' },
  { id: 'wisdom-5', category: 'wisdom', text: 'Honesty is the first chapter in the book of wisdom.', author: 'Thomas Jefferson' },
  { id: 'wisdom-6', category: 'wisdom', text: 'A wise man can learn more from a foolish question than a fool can learn from a wise answer.', author: 'Bruce Lee' },
  { id: 'wisdom-7', category: 'wisdom', text: 'Obstacles don\'t have to stop you. If you run into a wall, don\'t turn around and give up. Figure out how to climb it, go through it, or work around it.', author: 'Michael Jordan' },
  { id: 'wisdom-8', category: 'wisdom', text: 'He who knows all the answers has not been asked all the questions.', author: 'Confucius' },
  { id: 'wisdom-9', category: 'wisdom', text: 'The smallest deed is better than the greatest intention.', author: 'John Burroughs' },
  { id: 'wisdom-10', category: 'wisdom', text: 'Better to remain silent and be thought a fool than to speak out and remove all doubt.', author: 'Abraham Lincoln' },
  { id: 'wisdom-11', category: 'wisdom', text: 'How we spend our days is, of course, how we spend our lives.', author: 'Annie Dillard' },
  { id: 'wisdom-12', category: 'wisdom', text: 'It\'s better to be a lion for a day than a sheep all your life.', author: 'Elizabeth Kenny' },
  { id: 'wisdom-13', category: 'wisdom', text: 'The simple things are also the most extraordinary things, and only the wise can see them.', author: 'Paulo Coelho' },
  { id: 'wisdom-14', category: 'wisdom', text: 'Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.', author: 'Martin Luther' },
  { id: 'wisdom-15', category: 'wisdom', text: 'One good thing about music, when it hits you, you feel no pain.', author: 'Bob Marley' },
  { id: 'wisdom-16', category: 'wisdom', text: 'The limits of my language mean the limits of my world.', author: 'Ludwig Wittgenstein' },
  { id: 'wisdom-17', category: 'wisdom', text: 'The only thing necessary for the triumph of evil is for good men to do nothing.', author: 'Edmund Burke' },
  { id: 'wisdom-18', category: 'wisdom', text: 'The World is my country, all mankind are my brethren, and to do good is my religion.', author: 'Thomas Paine' },
  { id: 'wisdom-19', category: 'wisdom', text: 'He not busy being born is busy dying.', author: 'Bob Dylan' },
  { id: 'wisdom-20', category: 'wisdom', text: 'Your beliefs become your thoughts, your thoughts become your words, your words become your actions, your actions become your habits, your habits become your values, your values become your destiny.', author: 'Mahatma Gandhi' },
];

export function quotesForCategory(category: string): Quote[] {
  return QUOTES.filter((q) => q.category === category);
}
